name: mlx-edge
channels:
  - conda-forge
dependencies:
  - python >=3.11,<3.14
  - pip
  - git
  - mlx
  - mlx-lm
  - mlx-vlm
  - huggingface_hub
  - pip:
      - git+https://github.com/milljm/bleeding-edge-mlx-server.git
